# This file was generated by GoReleaser. DO NOT EDIT.
cask "godo" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "3332fc5d671ad8773fd8481869a1dc0b3af18f105574e3b4e2346878883f3638"
      url "https://github.com/MY-RV/godo/releases/download/v#{version}/godo_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2007d427e7d9d2e9f977fbebf5c0133b0b4fad3637e0daf42414ae55e58c2364"
      url "https://github.com/MY-RV/godo/releases/download/v#{version}/godo_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e847fb0e5d7969bb58ccbd3d08427a33760774c58eb25ff2e12b986ac7b30e81"
      url "https://github.com/MY-RV/godo/releases/download/v#{version}/godo_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7880122a644f0b17b2c33705ce0da662e6aca1da2de6f6e9698b2e7ede1723fb"
      url "https://github.com/MY-RV/godo/releases/download/v#{version}/godo_#{version}_linux_amd64.tar.gz"
    end
  end

  name "godo"
  desc "Thin repo command catalog"
  homepage "https://github.com/MY-RV/godo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "godo"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/godo"]
    end
  end

  # No zap stanza required
end
