# This file was generated by GoReleaser. DO NOT EDIT.
cask "hensu" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "c09ee1a18e58399238ee07f346ec498a4a37982ee478dadf8c9282d58c5d8e9f"
      url "https://github.com/MY-RV/hensu/releases/download/v#{version}/hensu_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b93ce56024559dbb91c1672c0a897c6fb2a7789137f347ceab693618e101e35c"
      url "https://github.com/MY-RV/hensu/releases/download/v#{version}/hensu_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d5741997af39e6b806844467fbab4a9e0588ca822af51c3f4718f3f654ebc474"
      url "https://github.com/MY-RV/hensu/releases/download/v#{version}/hensu_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "bbac0b2d45f1cbbb24cf335043ea474050585e437db468165bffdbff946e26d1"
      url "https://github.com/MY-RV/hensu/releases/download/v#{version}/hensu_#{version}_linux_amd64.tar.gz"
    end
  end

  name "hensu"
  desc "Machine-local config get/set/dump that agents can read without seeing values"
  homepage "https://github.com/MY-RV/hensu"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hensu"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hensu"]
    end
  end

  # No zap stanza required
end
