# This file was generated by GoReleaser. DO NOT EDIT.
cask "hensu" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "68f823696a7395af9c55f9af5e9bcbd5ed33fc615784007d6294a36fef460cfb"
      url "https://github.com/MY-RV/hensu/releases/download/v#{version}/hensu_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5abefa9fde195c9b9bdbaa25f72d982c278ba4ff11e8d8999615b62560cb420e"
      url "https://github.com/MY-RV/hensu/releases/download/v#{version}/hensu_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "62e7792e2b61e5272736ebe42c32155b5a48897de896a529a5d29e6bd001fbdf"
      url "https://github.com/MY-RV/hensu/releases/download/v#{version}/hensu_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "de389e1d70d3a2accfa85a02c54f01caf08def079e46b9def2e6086179f7424a"
      url "https://github.com/MY-RV/hensu/releases/download/v#{version}/hensu_#{version}_linux_amd64.tar.gz"
    end
  end

  name "hensu"
  desc "Machine-local config get/set/dump that agents can read without seeing values"
  homepage "https://github.com/MY-RV/hensu"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hensu"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hensu"]
    end
  end

  # No zap stanza required
end
